# Generated by Django 6.0.2 on 2026-02-19 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textrecord',
            name='created_at',
        ),
    ]
