# Generated by Django 6.0.2 on 2026-02-19 01:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_textrecord_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='textrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
